---
title: ""
---
<style>
  body {background-color:rgba(250, 250, 250)}
</style>


```{r echo=FALSE, message=FALSE, warning=FALSE}
##R Preamble
library(MacrobondAPI)
library(tidyverse)
library(zoo)
library(xts)
library(tsbox)
library(ggplot2)
library(plotly)
library(htmlwidgets)
library(htmltools)
library(dygraphs)
library(lubridate)
library(highcharter)
#library(gridExtra)
```

```{r echo=FALSE, message=FALSE, warning=FALSE, results="hide", fig.show='hide'}
##Gather the Electricity Data
electricity <- c("entso_loa_de_11_q1", "entso_loa_fr_11", "entso_loa_it_11", "entso_loa_es_11")
request_elec <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(electricity))
week_elec <- apply.weekly(request_elec, mean)

week_q <-  rollapply(week_elec, 4, mean)
week_el_index <- as.xts(apply(week_q,2, function(x)  x*100/x["2019-06-02"]))

colnames(week_el_index) <- c("Deutschland", "Frankreich", "Italien", "Spanien")
#tail(week_el_index)
## Merge US DATA
library(eia)
mykey <- "b6e4a42a8e85f78a8e1e4fcfd1d7f6dd"
eia_set_key(mykey)
id <- "EBA.US48-ALL.D.H"
d <- eia_series(id, n = 60000)

us_elec <- data.frame(d$data)
us_elec <- data.frame(us_elec$date,us_elec$value)
us_elec_ts <- ts_xts(us_elec)
us_day <- apply.daily(us_elec_ts,mean,1)
index(us_day)<- as.Date(unlist(lapply(strsplit(as.character(index(us_day))," "), function(x) x[1])))

us_week <- apply.weekly(us_day, mean)

us_12day <-  rollapply(us_week, 4, mean)
us_12day_index <- as.xts(apply(us_12day,2, function(x)  x*100/x["2019-06-02"]))

colnames(us_12day_index) <- c("USA")

elec_week_all <- merge(week_el_index["2015/"], us_12day_index["2015/"])
#tail(elec_week_all)

#plot(elec_week_all)

```

```{r echo=FALSE, message=FALSE, warning=FALSE, results="hide", fig.show='hide'}

elec_seas <- ts_df(elec_week_all$Deutschland)

p <- ggplot(elec_seas, aes(as.Date(yday(time)), 
                             value, group=factor(year(time)),
                             colour=factor(year(time)),
                            text   = paste('Year: ', factor(year(time)), '\n',
                                 'Index: ', sprintf("%0.2f", round(value, digits = 2)), '\n') )) +
        geom_line() +
        #geom_point() +
        labs(x="Month", colour="Year") +
        theme_classic()+
        scale_x_date(date_labels = "%b")+
       scale_color_manual(values=c("maroon", "gray", "navy", "orange", "red", "black")) +
       scale_size_manual(values = c(0.7, 0.7, 0.7, 0.7, 0.7,1.5))+
       theme_bw() +xlab("") + ylab("MWh, 02.06.2019 = 100")+
       theme(legend.title = element_blank())+
       theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
       theme(plot.title = element_text(hjust = 0.5), 
       plot.subtitle = element_text(hjust = 0.5)) +
       theme(plot.title = element_text(hjust = 0.5))

p_de_plot <- p + labs(title = "Stromverbrauch: Deutschland",
          caption = "Quelle: Flossbach von Storch Research Institute, \n ENTSO-E, EIA. Gleitender Monatsdurchschnitt")

### USA
elec_seas <- ts_df(elec_week_all$USA)
p <- ggplot(elec_seas, aes(as.Date(yday(time)), 
                             value, group=factor(year(time)),
                             colour=factor(year(time)),
                            text   = paste('Year: ', factor(year(time)), '\n',
                                 'Index: ', sprintf("%0.2f", round(value, digits = 2)), '\n') )) +
        geom_line() +
        #geom_point() +
        labs(x="Month", colour="Year") +
        theme_classic()+
        scale_x_date(date_labels = "%b")+
       scale_color_manual(values=c("maroon", "gray", "navy", "orange", "red", "black")) +
       scale_size_manual(values = c(0.7, 0.7, 0.7, 0.7, 0.7,1.5))+
       theme_bw() +xlab("") + ylab("MWh, 02.06.2019 = 100")+
       theme(legend.title = element_blank())+
       theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
       theme(plot.title = element_text(hjust = 0.5), 
       plot.subtitle = element_text(hjust = 0.5)) +
       theme(plot.title = element_text(hjust = 0.5))

p_us_plot <- p + labs(title = "Stromverbrauch: USA",
          caption = "Quelle: Flossbach von Storch Research Institute, \n ENTSO-E, EIA. Gleitender Monatsdurchschnitt")


### Italien
elec_seas <- ts_df(elec_week_all$Italien)

p <- ggplot(elec_seas, aes(as.Date(yday(time)), 
                             value, group=factor(year(time)),
                             colour=factor(year(time)),
                            text   = paste('Year: ', factor(year(time)), '\n',
                                 'Index: ', sprintf("%0.2f", round(value, digits = 2)), '\n') )) +
        geom_line() +
        #geom_point() +
        labs(x="Month", colour="Year") +
        theme_classic()+
        scale_x_date(date_labels = "%b")+
       scale_color_manual(values=c("maroon", "gray", "navy", "orange", "red", "black")) +
       scale_size_manual(values = c(0.7, 0.7, 0.7, 0.7, 0.7,1.5))+
       theme_bw() +xlab("") + ylab("MWh, 02.06.2019 = 100")+
       theme(legend.title = element_blank())+
       theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
       theme(plot.title = element_text(hjust = 0.5), 
       plot.subtitle = element_text(hjust = 0.5)) +
       theme(plot.title = element_text(hjust = 0.5))

p_it_plot <- p + labs(title = "Stromverbrauch: Italien",
          caption = "Quelle: Flossbach von Storch Research Institute, \n ENTSO-E, EIA. Gleitender Monatsdurchschnitt")


### frankreich
elec_seas <- ts_df(elec_week_all$Frankreich)

p <- ggplot(elec_seas, aes(as.Date(yday(time)), 
                             value, group=factor(year(time)),
                             colour=factor(year(time)),
                             text   = paste('Year: ', factor(year(time)), '\n',
                                 'Index: ', sprintf("%0.2f", round(value, digits = 2)), '\n') )) +
        geom_line() +
        #geom_point() +
        labs(x="Month", colour="Year") +
        theme_classic()+
        scale_x_date(date_labels = "%b")+
       scale_color_manual(values=c("maroon", "gray", "navy", "orange", "red", "black")) +
       scale_size_manual(values = c(0.7, 0.7, 0.7, 0.7, 0.7,1.7))+
       theme_bw() +xlab("") + ylab("MWh, 02.06.2019 = 100")+
       theme(legend.title = element_blank())+
       theme(panel.grid.major = element_blank(), panel.grid.minor = element_blank())+
       theme(plot.title = element_text(hjust = 0.5), 
       plot.subtitle = element_text(hjust = 0.5)) +
       theme(plot.title = element_text(hjust = 0.5))

p_fr_plot <- p + labs(title = "Stromverbrauch: Frankreich",
          caption = "Quelle: Flossbach von Storch Research Institute, \n ENTSO-E, EIA. Gleitender Monatsdurchschnitt")

```

```{r echo=FALSE, message=FALSE, warning=FALSE, results="hide", fig.show='hide'}
##GDP
gdp <- c("denaac0152", "frnaac0284", "itnaac0466", "esnaac0097", "eunaac2903", "usnaac0169", "cnnaac0001")
request_gdp <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(gdp))
colnames(request_gdp) <- c("Deutschland", "Frankreich", "Italien", "Spanien", "Eurozone", "USA", "China")
gdp_dif <- as.xts(apply(request_gdp,2, function(x)  100*(x / lag(x)-1)))
#index(gdp_dif) <- as.yearqtr(index(gdp_dif))
#index(gdp_dif) <- index(gdp_dif)+(1/4)

##Industrial Prod
iprod <- c("deprod1404","frprod0228","itprod0496","esprod0420", "euprod0001", "usprod1022", "cnprod1001")
request_iprod <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(iprod))
colnames(request_iprod) <- c("Deutschland", "Frankreich", "Italien", "Spanien", "Eurozone", "USA", "China")
iprod_nocn <- as.xts(request_iprod[,1:6])
iprod_cn <- as.xts(request_iprod[,7])
iprod_dif <- as.xts(apply(iprod_nocn,2, function(x)  100*(x / lag(x,n=12L)-1)), dateFormat="Date") #weird date stuff
iprod_all <- merge.xts(iprod_dif, iprod_cn )
```

```{r echo=FALSE, message=FALSE, warning=FALSE, results="hide", fig.show='hide'}
##CPI
cpi <- c("depric1962","frpric0611","itpric0286","espric4357", "eupric0001", "uspric2156", "cnpric0101")

request_cpi <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(cpi))
colnames(request_cpi) <- c("Deutschland", "Frankreich", "Italien", "Spanien", "Eurozone", "USA", "China")

cpi_nocn <- as.xts(request_cpi[,1:6])
cpi_cn <- as.xts(request_cpi[,7])
cpi_dif <- as.xts(apply(cpi_nocn,2, function(x)  100*(x / lag(x,n=12L)-1)), dateFormat="Date") 
cpi_cn_dif <- cpi_cn - 100
#weird date stuff
cpi_all <- merge.xts(cpi_dif, cpi_cn_dif)
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
##GDP Dynamic Graph
p_gdp <- highchart(type = "stock" ) %>% 
  hc_title(text = "BIP-Wachstum (QoQ%)") %>% 
 hc_subtitle(text = "Quelle: Flossbach von Storch Research Institute, Eurostat, nationale statistische Ämter") %>% 
   hc_exporting(enabled = TRUE) %>%
      hc_legend(enabled = TRUE) %>%
  hc_add_series(gdp_dif["200001/"]$Deutschland, name ="Deutschland") %>% 
  hc_add_series(gdp_dif["200001/"]$Frankreich, name = "Frankreich" ) %>% 
  hc_add_series(gdp_dif["200001/"]$Italien, name = "Italien") %>% 
  hc_add_series(gdp_dif["200001/"]$Spanien, name = "Spanien") %>% 
  hc_add_series(gdp_dif["200001/"]$USA, name = "USA") %>%
  hc_add_series(gdp_dif["200001/"]$China, name = "China") %>% 
  hc_colors(c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
  hc_rangeSelector(inputDateFormat = '%y-%m-%d', selected = 3) %>%
  hc_tooltip(valueDecimals= 2)%>%
  hc_chart(style = list(fontFamily = "BigVesta",
                        fontWeight = "bold"))

#dygraph(gdp_dif["200001/"], main = "BIP-Wachstum (QoQ%)", width = "80%")%>%
 # dyAxis("x", drawGrid = FALSE)%>%
 # dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))%>%
 # dyOptions(colors = c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
  #dyCSS("legend.css")%>%
  #dyLegend(labelsSeparateLines = TRUE)%>%
  #  dyRangeSelector(dateWindow = c("2018-08-01","2020-04-01"))%>%
  #dyUnzoom()
p_gdp
saveWidget(p_gdp, "C:/Users/DuarteP/Documents/web/real_tracker_fvs/01_gdp.html", background = "rgba(250, 250, 250)")
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
##Industrial production Dynamic Graph

p_iprod <- highchart(type = "stock" ) %>% 
  hc_title(text = "Industrieproduketion (YoY%)") %>% 
 hc_subtitle(text = "Quelle: Flossbach von Storch Research Institute,Eurostat, nationale statistische Ämter") %>% 
   hc_exporting(enabled = TRUE) %>%
      hc_legend(enabled = TRUE) %>%
  hc_add_series(iprod_all["200001/"]$Deutschland, name ="Deutschland") %>% 
  hc_add_series(iprod_all["200001/"]$Frankreich, name = "Frankreich" ) %>% 
  hc_add_series(iprod_all["200001/"]$Italien, name = "Italien") %>% 
  hc_add_series(iprod_all["200001/"]$Spanien, name = "Spanien") %>% 
  hc_add_series(iprod_all["200001/"]$USA, name = "USA") %>%
  hc_add_series(iprod_all["200001/"]$China, name = "China") %>% 

  hc_colors(c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
  hc_rangeSelector(inputDateFormat = '%y-%m-%d', selected = 3) %>%
  hc_tooltip(valueDecimals= 2)%>%
  hc_chart(style = list(fontFamily = "BigVesta",
                        fontWeight = "bold"))


p_iprod
saveWidget(p_iprod, "C:/Users/DuarteP/Documents/web/real_tracker_fvs/01_iprod.html", background = "rgba(250, 250, 250)")


#today <- as.character(Sys.Date())
#dygraph(iprod_all["200701/"], main = "Industrieproduketion (YoY%)", width = "80%")%>%
 # dyAxis("x", drawGrid = FALSE)%>%
  #dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))%>%
  #dyOptions(colors = c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
  #dyCSS("legend.css")%>%
  #dyLegend(labelsSeparateLines = TRUE)%>%
  #dyRangeSelector(dateWindow = c("2019-08-01",today))%>%
  #dyUnzoom()
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
##CPI Dynamic
p_cpi <- highchart(type = "stock" ) %>% 
  hc_title(text = "Verbraucherpreisindex (YoY%)") %>% 
 hc_subtitle(text = "Quelle: Flossbach von Storch Research Institute, Eurostat, nationale statistische Ämter") %>% 
   hc_exporting(enabled = TRUE) %>%
      hc_legend(enabled = TRUE) %>%
  hc_add_series(cpi_all["200001/"]$Deutschland, name ="Deutschland") %>% 
  hc_add_series(cpi_all["200001/"]$Frankreich, name = "Frankreich" ) %>% 
  hc_add_series(cpi_all["200001/"]$Italien, name = "Italien") %>% 
  hc_add_series(cpi_all["200001/"]$Spanien, name = "Spanien") %>% 
  hc_add_series(cpi_all["200001/"]$USA, name = "USA") %>%
  hc_add_series(cpi_all["200001/"]$China, name = "China") %>% 

  hc_colors(c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
  hc_rangeSelector(inputDateFormat = '%y-%m-%d', selected = 4) %>%
  hc_tooltip(valueDecimals= 2)%>%
  hc_chart(style = list(fontFamily = "BigVesta",
                        fontWeight = "bold"))


p_cpi
saveWidget(p_cpi, "C:/Users/DuarteP/Documents/web/real_tracker_fvs/01_cpi.html", background = "rgba(250, 250, 250)")

#today <- as.character(Sys.Date())
#dygraph(cpi_all["200701/"], main = "Verbraucherpreisindex (YoY%)", width = "80%")%>%
 # dyAxis("x", drawGrid = FALSE)%>%
#  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))%>%
#  dyOptions(colors = c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
#  dyCSS("legend.css")%>%
#  dyLegend(labelsSeparateLines = TRUE)%>%
#  dyRangeSelector(dateWindow = c("2018-11-01",today))%>%
#  dyUnzoom()
```

```{r echo=FALSE, message=FALSE, warning=FALSE}
trucks <- c("detran0225")
request_trucks <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(trucks))
colnames(request_trucks) <- c("Index")
trucks_ma <-  rollapply(request_trucks, 7, mean)
trucks_ma_index <- as.xts(apply(trucks_ma,2, function(x)  x*100/x["2020-02-01"]))


p_trucks <- highchart(type = "stock" ) %>% 
  hc_title(text = "Lkw-Maut-Fahrleistungsindex: Deutschland (02.2020 = 100)") %>% 
 hc_subtitle(text = "Quelle: Flossbach von Storch Research Institute, Statistisches Bundesamt.") %>% 
   hc_exporting(enabled = TRUE) %>%
      hc_legend(enabled = TRUE) %>%
  hc_add_series(trucks_ma_index, name ="") %>% 
    hc_colors(c("maroon","black", "gray", "navy", "orange", "red", "orange"))%>%
  hc_rangeSelector(inputDateFormat = '%y-%m-%d', selected = 1) %>%
  hc_tooltip(valueDecimals= 2)%>%
  hc_chart(style = list(fontFamily = "BigVesta",
                        fontWeight = "bold"))


p_trucks
saveWidget(p_trucks, "C:/Users/DuarteP/Documents/web/real_tracker_fvs/01_trucks.html", background = "rgba(250, 250, 250)")

#dygraph(trucks_ma["201902/"], main = "Lkw-Maut-Fahrleistungsindex: Deutschland", width = "80%")%>%
#dyAxis("x", drawGrid = FALSE)%>% 
#dyHighlight(highlightSeriesOpts = list(strokeWidth = 2))%>%
#dyOptions(colors = c("black","maroon", "gray", "navy", "orange"))%>%
#dyLegend(labelsSeparateLines = TRUE, show = "always")%>%
 # dyCSS("legend.css")%>%
 # dyRangeSelector(dateWindow = c("2020-02-01",today))%>%
 # dyUnzoom()
```


```{r echo=FALSE, message=FALSE, warning=FALSE}
##Electricity

electricity <- c("entso_loa_de_11_q1", "entso_loa_fr_11", "entso_loa_it_11", "entso_loa_es_11")
request_elec <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(electricity))
week_elec <-  rollapply(request_elec, 7, mean)
week_el_index <- as.xts(apply(week_elec,2, function(x)  x*100/x["2020-02-01"]))

colnames(week_el_index) <- c("Deutschland", "Frankreich", "Italien", "Spanien")

##China
electricity_cn <- c("cnprod0401")
request_elec_cn <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(electricity_cn))
week_elec_cn <-  request_elec_cn
week_el_index_cn <- as.xts(apply(week_elec_cn,2, function(x)  x*100/x["2020-02-01"]))

colnames(week_el_index_cn) <- c("China")

## Merge US DATA
library(eia)
mykey <- "b6e4a42a8e85f78a8e1e4fcfd1d7f6dd"
eia_set_key(mykey)
id <- "EBA.US48-ALL.D.H"
d <- eia_series(id, n = 10000)

us_elec <- data.frame(d$data)
us_elec <- data.frame(us_elec$date,us_elec$value)
us_elec_ts <- ts_xts(us_elec)
us_day <- apply.daily(us_elec_ts,mean,1)
index(us_day)<- as.Date(unlist(lapply(strsplit(as.character(index(us_day))," "), function(x) x[1])))

us_7day <-  rollapply(us_day, 7, mean)
us_7day_index <- as.xts(apply(us_7day,2, function(x)  x*100/x["2020-02-01"]))
colnames(us_7day_index) <- c("USA")

week_all_index <- merge(week_el_index, us_7day_index, week_el_index_cn)
week_all_index <-  rollapply(week_all_index, 52, mean)

```

```{r echo=FALSE, message=FALSE, warning=FALSE}
##Dynamic Graph

p_elec <- highchart(type = "stock" ) %>% 
  hc_title(text = "Stromverbrauch (01.02.2020 = 100)") %>% 
 hc_subtitle(text = "Quelle: Flossbach von Storch Research Institute, ENTSO-E, EIA, China NEA. Wochendurchschnitte.") %>% 
   hc_exporting(enabled = TRUE) %>%
      hc_legend(enabled = TRUE) %>%
  hc_add_series(week_all_index$Deutschland["201601/"], name ="Deutschland") %>% 
  hc_add_series(week_all_index$Frankreich["201601/"], name = "Frankreich" ) %>% 
  hc_add_series(week_all_index$Italien["201601/"], name = "Italien") %>% 
  hc_add_series(week_all_index$Spanien["201601/"], name = "Spanien") %>% 
  hc_add_series(week_all_index$USA["201601/"], name = "USA") %>%
  hc_colors(c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
  hc_rangeSelector(inputDateFormat = '%y-%m-%d', selected = 3) %>%
  hc_tooltip(valueDecimals= 2)%>%
  hc_chart(style = list(fontFamily = "BigVesta",
                        fontWeight = "bold"))


p_elec
saveWidget(p_elec, "C:/Users/DuarteP/Documents/web/real_tracker_fvs/01_elec.html", background = "rgba(250, 250, 250)")



#dygraph(week_all_index["201811/"], main = "Stromverbrauch (01.02.2020 = 100)", width = "80%")%>%
 # dyAxis("x", drawGrid = FALSE)%>%
#  dyHighlight(highlightSeriesOpts = list(strokeWidth = 3))%>%
#  dyOptions(colors = c("black","maroon", "gray", "navy", "orange", "red"))%>%
#  dyCSS("legend.css")%>%
#  dyLegend(labelsSeparateLines = TRUE)%>%
#  dySeries(na.omit("China"), stepPlot = TRUE, fillGraph = TRUE, color = "red")%>%
#  dyRangeSelector(dateWindow = c("2020-02-01",today))%>%
 # dyUnzoom()
```

```{r echo=FALSE, message= FALSE, warning=FALSE}
##China
china<- c("cnprod0401", "cnprod0185", "jodicngsdem_kbd")
request_cn <-MakeXtsFromUnifiedResponse(FetchUnifiedTimeSeriesDefault(china))
index_cn <- as.xts(apply(request_cn,2, function(x)  x*100/x["2019-11-01"]))

colnames(index_cn) <- c("Electricity", "Vehicle", "Gasoline")
index_cn <-  rollapply(index_cn, 12, mean)


p_china <- highchart(type = "stock" ) %>% 
  hc_title(text = "China (November 2019 = 100)") %>% 
 hc_subtitle(text = "Quelle: Flossbach von Storch Research Institute, China National Energy Association, Association of Automobile Manufacturers, Joint Organisations Data Initiative. Jahresdurchschnitte.") %>% 
   hc_exporting(enabled = TRUE) %>%
      hc_legend(enabled = TRUE) %>%
  hc_add_series(index_cn$Electricity["200501/"], name ="Electricity Consumption") %>% 
  hc_add_series(index_cn$Vehicle["200501/"], name = "Vehicle Production" ) %>% 
  hc_add_series(index_cn$Gasoline["200501/"], name = "Gasoline (Motor & Aviation)") %>% 
  hc_colors(c("black","maroon", "gray", "navy", "orange", "red", "orange"))%>%
  hc_rangeSelector(inputDateFormat = '%y-%m-%d', selected = 6) %>%
  hc_tooltip(valueDecimals= 2)%>%
  hc_chart(style = list(fontFamily = "BigVesta",
                        fontWeight = "bold"))


p_china
saveWidget(p_china, "C:/Users/DuarteP/Documents/web/real_tracker_fvs/01_china.html", background = "rgba(250, 250, 250)")


#dygraph(index_cn["201701/"], main = "China (November 2019 = 100)", width = "80%")%>%
#dyAxis("x", drawGrid = FALSE)%>% 
#dyHighlight(highlightSeriesOpts = list(strokeWidth = 2))%>%
#dyOptions(colors = c("black","maroon", "gray"))%>%
#dyCSS("legend.css")%>%
#  dyLegend(labelsSeparateLines = TRUE, show = "always")%>%
#dyRangeSelector()%>%
 # dyUnzoom()
```

